name = "xano-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-05-01"
account_id = "7eb97d8aafdc135db8eb1c18613dc170"
compatibility_flags = ["nodejs_compat"]

# For MCP agent
[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "MyMCP"

# For OAuth persistence
[[kv_namespaces]]
binding = "OAUTH_KV"
id = "c43c2dc2174244c8bb1d4e5bb9cf6fa4"

[[migrations]]
tag = "v1"
new_classes = ["MyMCP"]

# Environment variables
[vars]
XANO_BASE_URL = "https://xnwv-v1z6-dvnr.n7c.xano.io"
COOKIE_ENCRYPTION_KEY = "secure-oauth-cookie-encryption-key-for-xano-mcp"