name = "xano-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-05-01"
account_id = "91e4e6d01964d00df36b85bd7e1549eb"

# For authentication token storage
[[kv_namespaces]]
binding = "AUTH_TOKENS"
id = "71efbd627a12406c8f3be9ce60d5872d"

# For stateful session management
[[durable_objects.bindings]]
name = "SESSIONS"
class_name = "SessionObject"

[[migrations]]
tag = "v1"
new_classes = ["SessionObject"]

# Environment variables
[vars]
XANO_API_BASE = "https://your-xano-instance.com/api:your-api-id"